server:
  port: 8088
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/carloszeferino/microservices-tutorial.git
          search-paths: config-data
  application:
    name: config-service